<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressItemExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\Doctrine\QueryItemExtension\AddressItemExtension' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Doctrine\QueryItemExtension\AddressItemExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Extension/QueryItemExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/AddressItemExtension.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\Doctrine\\QueryItemExtension\\AddressItemExtension'] = new \Sylius\Bundle\ApiBundle\Doctrine\QueryItemExtension\AddressItemExtension(($container->services['Sylius\\Bundle\\ApiBundle\\Context\\UserContextInterface'] ?? $container->getUserContextInterfaceService()));
    }
}
