<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Form_Type_DraftAttributeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'bitbag_mvm_plugin.form.type.draftAttribute' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Form\ProductListing\DraftAttributeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ProductListing/DraftAttributeType.php';

        return $container->privates['bitbag_mvm_plugin.form.type.draftAttribute'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Form\ProductListing\DraftAttributeType('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\ProductListing\\DraftAttribute', $container->parameters['sylius.form.type.product_attribute.validation_groups'], 'BitBag\\SyliusMultiVendorMarketplacePlugin\\Form\\ProductListing\\DraftAttributeTranslationType', ($container->services['sylius.form_registry.attribute_type'] ?? $container->load('getSylius_FormRegistry_AttributeTypeService')));
    }
}
