<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Form_VendorTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'bitbag_mvm_plugin.form.vendor_type' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Form\Type\VendorType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/VendorType.php';

        return $container->privates['bitbag_mvm_plugin.form.vendor_type'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Form\Type\VendorType('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\ShopUser', ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()), 'BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\Vendor', $container->parameters['bitbag_mvm_plugin.form.type.vendor.validation_groups']);
    }
}
