<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Controller_Action_Conversation_CreateNewConversationActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag_mvm_plugin.controller.action.conversation.create_new_conversation_action' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Controller\Action\Conversation\CreateNewConversationAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/Conversation/CreateNewConversationAction.php';

        return $container->services['bitbag_mvm_plugin.controller.action.conversation.create_new_conversation_action'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Controller\Action\Conversation\CreateNewConversationAction(($container->services['.container.private.form.factory'] ?? $container->get_Container_Private_Form_FactoryService()), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->privates['api_platform.router'] ?? $container->getApiPlatform_RouterService()), ($container->privates['session.flash_bag'] ?? $container->load('getSession_FlashBagService')), ($container->privates['bitbag.sylius_multi_vendor_marketplace_plugin.facade.message.add_message_facade'] ?? $container->load('getBitbag_SyliusMultiVendorMarketplacePlugin_Facade_Message_AddMessageFacadeService')), ($container->services['bitbag_mvm_plugin.repository.conversation'] ?? $container->load('getBitbagMvmPlugin_Repository_ConversationService')));
    }
}
