<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Controller_EnableProductListingActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag_mvm_plugin.controller.enable_product_listing_action' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Controller\Action\Vendor\ProductListing\EnableProductListingAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/Vendor/ProductListing/EnableProductListingAction.php';

        return $container->services['bitbag_mvm_plugin.controller.enable_product_listing_action'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Controller\Action\Vendor\ProductListing\EnableProductListingAction(($container->services['bitbag_mvm_plugin.repository.product_listing'] ?? $container->load('getBitbagMvmPlugin_Repository_ProductListingService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['router'] ?? $container->getRouterService()), ($container->privates['session.flash_bag'] ?? $container->load('getSession_FlashBagService')));
    }
}
