<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbag_MvmPlugin_Factory_ProductTaxonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag.mvm_plugin.factory.product_taxon' shared service.
     *
     * @return \Sylius\Component\Resource\Factory\Factory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['bitbag.mvm_plugin.factory.product_taxon'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\ProductListing\\ProductDraftTaxon');
    }
}
