<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Factory_VendorProfileUpdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag_mvm_plugin.factory.vendor_profile_update' shared service.
     *
     * @return \Sylius\Component\Resource\Factory\Factory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['bitbag_mvm_plugin.factory.vendor_profile_update'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\VendorProfileUpdate');
    }
}
