<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbag_MvmPlugin_Fixture_OrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag.mvm_plugin.fixture.order' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Fixture\OrderFixture
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Definition/ConfigurationInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/src/Fixture/OrderFixture.php';

        return $container->services['bitbag.mvm_plugin.fixture.order'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Fixture\OrderFixture(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['bitbag.mvm_plugin.fixture.example_factory.order'] ?? $container->load('getBitbag_MvmPlugin_Fixture_ExampleFactory_OrderService')));
    }
}
