<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Repository_ConversationCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag_mvm_plugin.repository.conversation_category' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\Conversation\CategoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/Conversation/CategoryRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Conversation/CategoryRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        return $container->services['bitbag_mvm_plugin.repository.conversation_category'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\Conversation\CategoryRepository($a, $a->getClassMetadata('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\Conversation\\Category'));
    }
}
