<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatalogPromotionEligibilityCheckerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\CoreBundle\CatalogPromotion\Checker\CatalogPromotionEligibilityChecker' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\CatalogPromotion\Checker\CatalogPromotionEligibilityChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/CatalogPromotion/Checker/CatalogPromotionEligibilityCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/CatalogPromotion/Checker/CatalogPromotionEligibilityChecker.php';

        return $container->services['Sylius\\Bundle\\CoreBundle\\CatalogPromotion\\Checker\\CatalogPromotionEligibilityChecker'] = new \Sylius\Bundle\CoreBundle\CatalogPromotion\Checker\CatalogPromotionEligibilityChecker(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['sylius.catalog_promotion.criteria.enabled'] ?? ($container->services['sylius.catalog_promotion.criteria.enabled'] = new \Sylius\Bundle\PromotionBundle\Criteria\Enabled()));
            yield 1 => ($container->services['sylius.catalog_promotion.criteria.date_range'] ?? $container->load('getSylius_CatalogPromotion_Criteria_DateRangeService'));
        }, 2));
    }
}
