<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChangePaymentMethodHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\CommandHandler\Account\ChangePaymentMethodHandler' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\CommandHandler\Account\ChangePaymentMethodHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/CommandHandler/Account/ChangePaymentMethodHandler.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\CommandHandler\\Account\\ChangePaymentMethodHandler'] = new \Sylius\Bundle\ApiBundle\CommandHandler\Account\ChangePaymentMethodHandler(($container->privates['Sylius\\Bundle\\ApiBundle\\Changer\\PaymentMethodChangerInterface'] ?? $container->load('getPaymentMethodChangerInterfaceService')), ($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()));
    }
}
