<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Sylius\Bundle\ThemeBundle\Command\ListCommand' shared service.
     *
     * @return \Sylius\Bundle\ThemeBundle\Command\ListCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Command/ListCommand.php';

        return $container->services['console.command.public_alias.Sylius\\Bundle\\ThemeBundle\\Command\\ListCommand'] = new \Sylius\Bundle\ThemeBundle\Command\ListCommand(($container->privates['Sylius\\Bundle\\ThemeBundle\\Repository\\ThemeRepositoryInterface'] ?? $container->getThemeRepositoryInterfaceService()));
    }
}
