<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMvm_Form_Type_ConversationMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mvm.form.type.conversation_message' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Form\Type\Conversation\MessageType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/Conversation/MessageType.php';

        return $container->privates['mvm.form.type.conversation_message'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Form\Type\Conversation\MessageType();
    }
}
