<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'BitBag\SyliusMultiVendorMarketplacePlugin\Repository\Conversation\MessageRepository' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\Conversation\MessageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/Conversation/MessageRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Conversation/MessageRepository.php';

        return $container->privates['BitBag\\SyliusMultiVendorMarketplacePlugin\\Repository\\Conversation\\MessageRepository'] = $container->get('bitbag_multi_vendor_marketplace.repository.conversation_message');
    }
}
