<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNamespacedTemplateLocatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ThemeBundle\Twig\Locator\NamespacedTemplateLocator' shared service.
     *
     * @return \Sylius\Bundle\ThemeBundle\Twig\Locator\NamespacedTemplateLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Twig/Locator/NamespacedTemplateLocator.php';

        return $container->privates['Sylius\\Bundle\\ThemeBundle\\Twig\\Locator\\NamespacedTemplateLocator'] = new \Sylius\Bundle\ThemeBundle\Twig\Locator\NamespacedTemplateLocator(($container->services['.container.private.filesystem'] ?? ($container->services['.container.private.filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));
    }
}
