<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'BitBag\SyliusMultiVendorMarketplacePlugin\Repository\OrderRepository' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\OrderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['BitBag\\SyliusMultiVendorMarketplacePlugin\\Repository\\OrderRepository'] = $container->get('sylius.repository.order');
    }
}
