<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayum_Extension_LogExecutedActionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payum.extension.log_executed_actions' shared service.
     *
     * @return \Payum\Core\Bridge\Psr\Log\LogExecutedActionsExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Bridge/Psr/Log/LogExecutedActionsExtension.php';

        return $container->services['payum.extension.log_executed_actions'] = new \Payum\Core\Bridge\Psr\Log\LogExecutedActionsExtension(($container->privates['monolog.logger.payum'] ?? $container->load('getMonolog_Logger_PayumService')));
    }
}
