<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductVariantFactoryInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Component\Product\Factory\ProductVariantFactoryInterface' shared service.
     *
     * @return \Sylius\Component\Product\Factory\ProductVariantFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Factory/ProductVariantFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Factory/ProductVariantFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/Factory/TranslatableFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/Factory/TranslatableFactory.php';

        return $container->services['Sylius\\Component\\Product\\Factory\\ProductVariantFactoryInterface'] = new \Sylius\Component\Product\Factory\ProductVariantFactory(new \Sylius\Component\Resource\Factory\TranslatableFactory(new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Core\\Model\\ProductVariant'), ($container->services['sylius.translation_locale_provider.admin'] ?? $container->load('getSylius_TranslationLocaleProvider_AdminService'))));
    }
}
