<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductListingRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'BitBag\SyliusMultiVendorMarketplacePlugin\Repository\ProductListing\ProductListingRepository' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\ProductListing\ProductListingRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ProductListing/ProductListingRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/ProductListing/ProductListingRepository.php';

        return $container->privates['BitBag\\SyliusMultiVendorMarketplacePlugin\\Repository\\ProductListing\\ProductListingRepository'] = $container->get('bitbag_mvm_plugin.repository.product_listing');
    }
}
