<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPickupCartLocaleValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\Validator\Constraints\PickupCartLocaleValidator' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Validator\Constraints\PickupCartLocaleValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Validator/Constraints/PickupCartLocaleValidator.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\Validator\\Constraints\\PickupCartLocaleValidator'] = new \Sylius\Bundle\ApiBundle\Validator\Constraints\PickupCartLocaleValidator(($container->services['sylius.repository.channel'] ?? $container->getSylius_Repository_ChannelService()));
    }
}
