<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_ShipmentShipService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.shipment_ship' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\EventListener\ShipmentShipListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/EventListener/ShipmentShipListener.php';

        return $container->services['sylius.listener.shipment_ship'] = new \Sylius\Bundle\AdminBundle\EventListener\ShipmentShipListener(($container->services['sylius.email_manager.shipment'] ?? $container->load('getSylius_EmailManager_ShipmentService')));
    }
}
