<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_UserLoginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.user_login' shared service.
     *
     * @return \Sylius\Bundle\UserBundle\Form\Type\UserLoginType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/Form/Type/UserLoginType.php';

        return $container->services['sylius.form.type.user_login'] = new \Sylius\Bundle\UserBundle\Form\Type\UserLoginType();
    }
}
