<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_CustomerProfileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.customer_profile' shared service.
     *
     * @return \Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerProfileType.php';

        return $container->services['sylius.form.type.customer_profile'] = new \Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType('Sylius\\Component\\Core\\Model\\Customer', $container->parameters['sylius.form.type.customer_profile.validation_groups']);
    }
}
