<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_OrderCustomerIpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.order_customer_ip' shared service.
     *
     * @return \Sylius\Bundle\ShopBundle\EventListener\OrderCustomerIpListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EventListener/OrderCustomerIpListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Assigner/IpAssignerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Assigner/CustomerIpAssigner.php';

        return $container->services['sylius.listener.order_customer_ip'] = new \Sylius\Bundle\ShopBundle\EventListener\OrderCustomerIpListener(($container->services['sylius.customer_ip_assigner'] ?? ($container->services['sylius.customer_ip_assigner'] = new \Sylius\Bundle\CoreBundle\Assigner\CustomerIpAssigner())), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
