<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_TranslationLocaleProvider_AdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.translation_locale_provider.admin' shared service.
     *
     * @return \Sylius\Component\Core\Provider\TranslationLocaleProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/Translation/Provider/TranslationLocaleProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Provider/TranslationLocaleProvider.php';

        return $container->services['sylius.translation_locale_provider.admin'] = new \Sylius\Component\Core\Provider\TranslationLocaleProvider(($container->services['sylius.repository.locale'] ?? $container->getSylius_Repository_LocaleService()), 'en_US');
    }
}
