<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_EmailRenderer_Adapter_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.email_renderer.adapter.default' shared service.
     *
     * @return \Sylius\Bundle\MailerBundle\Renderer\Adapter\EmailDefaultAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mailer-bundle/src/Component/Renderer/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mailer-bundle/src/Component/Renderer/Adapter/AbstractAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mailer-bundle/src/Bundle/Renderer/Adapter/EmailDefaultAdapter.php';

        $container->services['sylius.email_renderer.adapter.default'] = $instance = new \Sylius\Bundle\MailerBundle\Renderer\Adapter\EmailDefaultAdapter();

        if ($container->has('event_dispatcher')) {
            $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        }

        return $instance;
    }
}
