<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_ProportionalIntegerDistributorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.proportional_integer_distributor' shared service.
     *
     * @return \Sylius\Component\Core\Distributor\ProportionalIntegerDistributor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Distributor/ProportionalIntegerDistributorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Distributor/ProportionalIntegerDistributor.php';

        return $container->services['sylius.proportional_integer_distributor'] = new \Sylius\Component\Core\Distributor\ProportionalIntegerDistributor();
    }
}
