<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_CheckoutAddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.checkout_address' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Form\Type\Checkout\AddressType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Comparator/AddressComparatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Comparator/AddressComparator.php';

        return $container->services['sylius.form.type.checkout_address'] = new \Sylius\Bundle\CoreBundle\Form\Type\Checkout\AddressType('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\Order', $container->parameters['sylius.form.type.checkout_address.validation_groups'], ($container->services['sylius.address_comparator'] ?? ($container->services['sylius.address_comparator'] = new \Sylius\Component\Addressing\Comparator\AddressComparator())));
    }
}
