<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_TaxationAddressResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.taxation_address_resolver' shared service.
     *
     * @return \Sylius\Component\Core\Resolver\TaxationAddressResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Resolver/TaxationAddressResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Resolver/TaxationAddressResolver.php';

        return $container->services['sylius.taxation_address_resolver'] = new \Sylius\Component\Core\Resolver\TaxationAddressResolver(false);
    }
}
