<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Fixture_ExampleFactory_TaxonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.fixture.example_factory.taxon' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Fixture\Factory\TaxonExampleFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Generator/TaxonSlugGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php';

        return $container->services['sylius.fixture.example_factory.taxon'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\TaxonExampleFactory(($container->services['Sylius\\Component\\Taxonomy\\Factory\\TaxonFactoryInterface'] ?? $container->load('getTaxonFactoryInterfaceService')), ($container->services['sylius.repository.taxon'] ?? $container->load('getSylius_Repository_TaxonService')), ($container->services['sylius.repository.locale'] ?? $container->getSylius_Repository_LocaleService()), ($container->services['sylius.generator.taxon_slug'] ?? ($container->services['sylius.generator.taxon_slug'] = new \Sylius\Component\Taxonomy\Generator\TaxonSlugGenerator())));
    }
}
