<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Factory_AddToCartCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.factory.add_to_cart_command' shared service.
     *
     * @return \Sylius\Bundle\OrderBundle\Factory\AddToCartCommandFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Factory/AddToCartCommandFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Factory/AddToCartCommandFactory.php';

        return $container->services['sylius.factory.add_to_cart_command'] = new \Sylius\Bundle\OrderBundle\Factory\AddToCartCommandFactory();
    }
}
