<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_CustomerDefaultAddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.customer_default_address' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\CustomerDefaultAddressListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/CustomerDefaultAddressListener.php';

        return $container->services['sylius.listener.customer_default_address'] = new \Sylius\Bundle\CoreBundle\EventListener\CustomerDefaultAddressListener();
    }
}
