<?php

namespace ContainerAWYi9u6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_PromotionActionChoiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.promotion_action_choice' shared service.
     *
     * @return \Sylius\Bundle\PromotionBundle\Form\Type\PromotionActionChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionActionChoiceType.php';

        return $container->services['sylius.form.type.promotion_action_choice'] = new \Sylius\Bundle\PromotionBundle\Form\Type\PromotionActionChoiceType($container->parameters['sylius.promotion_actions']);
    }
}
