<?php

namespace Proxies\__CG__\BitBag\SyliusMultiVendorMarketplacePlugin\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vendor extends \BitBag\SyliusMultiVendorMarketplacePlugin\Entity\Vendor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'shopUser', 'companyName', 'taxIdentifier', 'phoneNumber', 'vendorAddress', 'status', 'enabled', 'editedAt', 'slug', 'description', 'image', 'products', 'productListings', 'shippingMethods'];
        }

        return ['__isInitialized__', 'id', 'shopUser', 'companyName', 'taxIdentifier', 'phoneNumber', 'vendorAddress', 'status', 'enabled', 'editedAt', 'slug', 'description', 'image', 'products', 'productListings', 'shippingMethods'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vendor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(?int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyName', []);

        return parent::getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyName(?string $companyName): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyName', [$companyName]);

        parent::setCompanyName($companyName);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxIdentifier(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxIdentifier', []);

        return parent::getTaxIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxIdentifier(?string $taxIdentifier): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxIdentifier', [$taxIdentifier]);

        parent::setTaxIdentifier($taxIdentifier);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber(?string $phoneNumber): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phoneNumber]);

        parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendorAddress(): ?\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\VendorAddressInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendorAddress', []);

        return parent::getVendorAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setVendorAddress(?\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\VendorAddressInterface $vendorAddress): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVendorAddress', [$vendorAddress]);

        parent::setVendorAddress($vendorAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getShopUser(): \BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ShopUserInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopUser', []);

        return parent::getShopUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setShopUser(\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ShopUserInterface $user): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShopUser', [$user]);

        parent::setShopUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', []);

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled(bool $enabled): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditedAt', []);

        return parent::getEditedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditedAt(?\DateTimeInterface $editedAt): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditedAt', [$editedAt]);

        parent::setEditedAt($editedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductListings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductListings', []);

        return parent::getProductListings();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductListings(\Doctrine\Common\Collections\Collection $productListings): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductListings', [$productListings]);

        parent::setProductListings($productListings);
    }

    /**
     * {@inheritDoc}
     */
    public function addProductListing(\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductListing\ProductListing $productListings): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductListing', [$productListings]);

        parent::addProductListing($productListings);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(?string $slug): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', []);

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct(\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductInterface $product): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct', [$product]);

        parent::addProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct(\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductInterface $product): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', [$product]);

        parent::removeProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\VendorImageInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(?\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\VendorImageInterface $image): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', []);

        parent::removeImage();
    }

    /**
     * {@inheritDoc}
     */
    public function isVerified(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVerified', []);

        return parent::isVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethods(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethods', []);

        return parent::getShippingMethods();
    }

    /**
     * {@inheritDoc}
     */
    public function hasShippingMethod(\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\VendorShippingMethodInterface $shippingMethod): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasShippingMethod', [$shippingMethod]);

        return parent::hasShippingMethod($shippingMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function addShippingMethod(\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\VendorShippingMethodInterface $shippingMethod): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addShippingMethod', [$shippingMethod]);

        parent::addShippingMethod($shippingMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function removeShippingMethod(\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\VendorShippingMethodInterface $shippingMethod): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeShippingMethod', [$shippingMethod]);

        parent::removeShippingMethod($shippingMethod);
    }

}
