<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EfAuiVqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.efAuiVq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.efAuiVq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'main' => ['privates', 'messenger.transport.main', 'getMessenger_Transport_MainService', true],
            'messenger.transport.main' => ['privates', 'messenger.transport.main', 'getMessenger_Transport_MainService', true],
        ], [
            'main' => '?',
            'messenger.transport.main' => '?',
        ]);
    }
}
