<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssets_PackageShopService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'assets._package_shop' shared service.
     *
     * @return \Sylius\Bundle\ThemeBundle\Asset\Package\PathPackage
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['assets._package_shop'] = new \Sylius\Bundle\ThemeBundle\Asset\Package\PathPackage('', new \Symfony\Component\Asset\VersionStrategy\JsonManifestVersionStrategy((\dirname(__DIR__, 4).'/public/build/shop/manifest.json'), NULL, false), ($container->privates['sylius.theme.context.channel_based'] ?? $container->getSylius_Theme_Context_ChannelBasedService()), ($container->privates['Sylius\\Bundle\\ThemeBundle\\Asset\\PathResolverInterface'] ?? $container->getPathResolverInterfaceService()), ($container->privates['assets.context'] ?? $container->getAssets_ContextService()));
    }
}
