<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetsInstallCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Sylius\Bundle\ThemeBundle\Command\AssetsInstallCommand' shared service.
     *
     * @return \Sylius\Bundle\ThemeBundle\Command\AssetsInstallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Command/AssetsInstallCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/Installer/AssetsInstallerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/Installer/OutputAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/Installer/OutputAwareAssetsInstaller.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/Installer/AssetsInstaller.php';

        return $container->services['console.command.public_alias.Sylius\\Bundle\\ThemeBundle\\Command\\AssetsInstallCommand'] = new \Sylius\Bundle\ThemeBundle\Command\AssetsInstallCommand(new \Sylius\Bundle\ThemeBundle\Asset\Installer\OutputAwareAssetsInstaller(new \Sylius\Bundle\ThemeBundle\Asset\Installer\AssetsInstaller(($container->services['.container.private.filesystem'] ?? ($container->services['.container.private.filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->privates['Sylius\\Bundle\\ThemeBundle\\Repository\\ThemeRepositoryInterface'] ?? $container->getThemeRepositoryInterfaceService()), ($container->privates['Sylius\\Bundle\\ThemeBundle\\Asset\\PathResolverInterface'] ?? $container->getPathResolverInterfaceService()), ($container->privates['Sylius\\Bundle\\ThemeBundle\\Asset\\Installer\\AssetsProviderInterface'] ?? $container->getAssetsProviderInterfaceService()))), \dirname(__DIR__, 4));
    }
}
