<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressMapperInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\Mapper\AddressMapperInterface' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Mapper\AddressMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Mapper/AddressMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Mapper/AddressMapper.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\Mapper\\AddressMapperInterface'] = new \Sylius\Bundle\ApiBundle\Mapper\AddressMapper();
    }
}
