<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbag_MvmPlugin_Fixture_ProductDraftService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag.mvm_plugin.fixture.product_draft' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Fixture\ProductDraftFixture
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Definition/ConfigurationInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/src/Fixture/ProductDraftFixture.php';

        return $container->services['bitbag.mvm_plugin.fixture.product_draft'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Fixture\ProductDraftFixture(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['bitbag.mvm_plugin.fixture.example_factory.product_draft'] ?? $container->load('getBitbag_MvmPlugin_Fixture_ExampleFactory_ProductDraftService')));
    }
}
