<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Controller_Conversation_ConversationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag_mvm_plugin.controller.conversation.conversation_controller' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Controller\Conversation\ConversationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Conversation/ConversationController.php';

        return $container->services['bitbag_mvm_plugin.controller.conversation.conversation_controller'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Controller\Conversation\ConversationController(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['.container.private.form.factory'] ?? $container->get_Container_Private_Form_FactoryService()), ($container->services['bitbag_mvm_plugin.repository.conversation'] ?? $container->load('getBitbagMvmPlugin_Repository_ConversationService')), ($container->privates['bitbag_mvm_plugin.current_user_resolver'] ?? $container->load('getBitbagMvmPlugin_CurrentUserResolverService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
