<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Form_VendorShippingMethodsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'bitbag_mvm_plugin.form.vendor_shipping_methods_type' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Form\Type\VendorShippingMethodsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/VendorShippingMethodsType.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/VendorShippingMethodFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/VendorShippingMethodFactory.php';

        return $container->privates['bitbag_mvm_plugin.form.vendor_shipping_methods_type'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Form\Type\VendorShippingMethodsType(($container->services['sylius.repository.shipping_method'] ?? $container->getSylius_Repository_ShippingMethodService()), ($container->privates['bitbag_mvm_plugin.factory.vendor_shipping_method'] ?? ($container->privates['bitbag_mvm_plugin.factory.vendor_shipping_method'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Factory\VendorShippingMethodFactory())), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), 'BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\Vendor');
    }
}
