<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbag_MvmPlugin_Controller_ShowVendorPageActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag.mvm_plugin.controller.show_vendor_page_action' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Controller\Action\Vendor\ShowVendorPageAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Action/Vendor/ShowVendorPageAction.php';

        $container->services['bitbag.mvm_plugin.controller.show_vendor_page_action'] = $instance = new \BitBag\SyliusMultiVendorMarketplacePlugin\Controller\Action\Vendor\ShowVendorPageAction(($container->services['bitbag.mvm_plugin.repository.vendor_repository'] ?? $container->load('getBitbag_MvmPlugin_Repository_VendorRepositoryService')), ($container->services['sylius.repository.product'] ?? $container->load('getSylius_Repository_ProductService')), ($container->services['Sylius\\Component\\Channel\\Context\\ChannelContextInterface'] ?? $container->getChannelContextInterfaceService()));

        $instance->setContainer($container);

        return $instance;
    }
}
