<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMultiVendorMarketplace_Factory_VendorProfileUpdateImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag_multi_vendor_marketplace.factory.vendor_profile_update_image' shared service.
     *
     * @return \Sylius\Component\Resource\Factory\Factory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['bitbag_multi_vendor_marketplace.factory.vendor_profile_update_image'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\VendorProfileUpdateImage');
    }
}
