<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Repository_ConversationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag_mvm_plugin.repository.conversation' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\Conversation\ConversationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/Conversation/ConversationRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Conversation/ConversationRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        return $container->services['bitbag_mvm_plugin.repository.conversation'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\Conversation\ConversationRepository($a, $a->getClassMetadata('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\Conversation\\Conversation'));
    }
}
