<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Factory_ProductListingFromDraftFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'bitbag_mvm_plugin.factory.product_listing_from_draft_factory' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Factory\ProductListingFromDraftFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Factory/ProductListingFromDraftFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Factory/ProductListingFromDraftFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Cloner/ProductListingTranslationClonerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Cloner/ProductListingTranslationCloner.php';
        include_once \dirname(__DIR__, 4).'/src/Cloner/ProductListingPricingClonerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Cloner/ProductListingPricingCloner.php';

        return $container->privates['bitbag_mvm_plugin.factory.product_listing_from_draft_factory'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Factory\ProductListingFromDraftFactory(($container->services['bitbag_mvm_plugin.factory.product_listing'] ?? ($container->services['bitbag_mvm_plugin.factory.product_listing'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\ProductListing\\ProductListing'))), ($container->services['bitbag_mvm_plugin.factory.product_draft'] ?? ($container->services['bitbag_mvm_plugin.factory.product_draft'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\ProductListing\\ProductDraft'))), new \BitBag\SyliusMultiVendorMarketplacePlugin\Cloner\ProductListingTranslationCloner(($container->services['bitbag_mvm_plugin.factory.product_translation'] ?? ($container->services['bitbag_mvm_plugin.factory.product_translation'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\ProductListing\\ProductTranslation')))), new \BitBag\SyliusMultiVendorMarketplacePlugin\Cloner\ProductListingPricingCloner(($container->services['bitbag_mvm_plugin.factory.product_listing_price'] ?? ($container->services['bitbag_mvm_plugin.factory.product_listing_price'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\ProductListing\\ProductListingPrice')))));
    }
}
