<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_CurrentUserResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'bitbag_mvm_plugin.current_user_resolver' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Resolver\CurrentUserResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Resolver/CurrentUserResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Resolver/CurrentUserResolver.php';

        return $container->privates['bitbag_mvm_plugin.current_user_resolver'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Resolver\CurrentUserResolver(($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
