<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Form_ProductListing_DraftAttributeValueTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'bitbag_mvm_plugin.form.product_listing.draft_attribute_value_type' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Form\ProductListing\DraftAttributeValueType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AttributeBundle/Form/Type/AttributeValueType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ProductListing/DraftAttributeValueType.php';

        return $container->privates['bitbag_mvm_plugin.form.product_listing.draft_attribute_value_type'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Form\ProductListing\DraftAttributeValueType('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\ProductListing\\DraftAttributeValue', $container->parameters['sylius.form.type.product_attribute_value.validation_groups'], 'BitBag\\SyliusMultiVendorMarketplacePlugin\\Form\\ProductListing\\DraftAttributeChoiceType', ($container->services['bitbag_mvm_plugin.repository.draft_attribute'] ?? $container->load('getBitbagMvmPlugin_Repository_DraftAttributeService')), ($container->services['sylius.repository.locale'] ?? $container->getSylius_Repository_LocaleService()), ($container->services['sylius.form_registry.attribute_type'] ?? $container->load('getSylius_FormRegistry_AttributeTypeService')));
    }
}
