<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Repository_ProductTranslationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'bitbag_mvm_plugin.repository.product_translation' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\ProductListing\ProductTranslationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ProductListing/ProductTranslationRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/ProductListing/ProductTranslationRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        return $container->privates['bitbag_mvm_plugin.repository.product_translation'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\ProductListing\ProductTranslationRepository($a, $a->getClassMetadata('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\ProductListing\\ProductListing'));
    }
}
