<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbagMvmPlugin_Factory_ProductListingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'bitbag_mvm_plugin.factory.product_listing' shared service.
     *
     * @return \Sylius\Component\Resource\Factory\Factory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['bitbag_mvm_plugin.factory.product_listing'] = new \Sylius\Component\Resource\Factory\Factory('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\ProductListing\\ProductListing');
    }
}
