<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBitbag_Form_Type_SyliusProductAssociationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'bitbag.form.type.sylius_product_associations' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Form\ProductListing\ProductAssociationsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ProductListing/ProductAssociationsType.php';

        return $container->privates['bitbag.form.type.sylius_product_associations'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Form\ProductListing\ProductAssociationsType(($container->services['sylius.repository.product_association_type'] ?? $container->load('getSylius_Repository_ProductAssociationTypeService')), ($container->services['sylius.form.type.data_transformer.products_to_product_associations'] ?? $container->load('getSylius_Form_Type_DataTransformer_ProductsToProductAssociationsService')));
    }
}
