<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'BitBag\SyliusMultiVendorMarketplacePlugin\Repository\CustomerRepository' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\CustomerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Repository/CustomerRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/CustomerRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/CustomerRepository.php';

        return $container->privates['BitBag\\SyliusMultiVendorMarketplacePlugin\\Repository\\CustomerRepository'] = $container->get('sylius.repository.customer');
    }
}
