<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDelayStampCalculatorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\CoreBundle\Calculator\DelayStampCalculatorInterface' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Calculator\DelayStampCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Calculator/DelayStampCalculatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Calculator/DelayStampCalculator.php';

        return $container->services['Sylius\\Bundle\\CoreBundle\\Calculator\\DelayStampCalculatorInterface'] = new \Sylius\Bundle\CoreBundle\Calculator\DelayStampCalculator();
    }
}
