<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderAdjustmentsSubresourceDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\DataProvider\OrderAdjustmentsSubresourceDataProvider' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\DataProvider\OrderAdjustmentsSubresourceDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/DataProvider/OrderAdjustmentsSubresourceDataProvider.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\DataProvider\\OrderAdjustmentsSubresourceDataProvider'] = new \Sylius\Bundle\ApiBundle\DataProvider\OrderAdjustmentsSubresourceDataProvider(($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()));
    }
}
