<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_CommandBus_Middleware_HandleMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.command_bus.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        $container->privates['sylius.command_bus.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Sylius\\Bundle\\CoreBundle\\CatalogPromotion\\Command\\ApplyCatalogPromotionsOnVariants' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.3fGyead'] ?? $container->load('get_Messenger_HandlerDescriptor_3fGyeadService'));
        }, 1), 'Sylius\\Bundle\\CoreBundle\\CatalogPromotion\\Command\\UpdateCatalogPromotionState' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.yZQZC2v'] ?? $container->load('get_Messenger_HandlerDescriptor_YZQZC2vService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\RegisterShopUser' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.A2MvrRI'] ?? $container->load('get_Messenger_HandlerDescriptor_A2MvrRIService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Cart\\PickupCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.P7AdpFk'] ?? $container->load('get_Messenger_HandlerDescriptor_P7AdpFkService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Cart\\AddItemToCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.0xzlWIZ'] ?? $container->load('get_Messenger_HandlerDescriptor_0xzlWIZService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Cart\\RemoveItemFromCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.cfnWDjm'] ?? $container->load('get_Messenger_HandlerDescriptor_CfnWDjmService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\UpdateCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.PrDVaXX'] ?? $container->load('get_Messenger_HandlerDescriptor_PrDVaXXService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\ChooseShippingMethod' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.8T.AZ2y'] ?? $container->load('get_Messenger_HandlerDescriptor_8T_AZ2yService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\ChoosePaymentMethod' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.34eMvh4'] ?? $container->load('get_Messenger_HandlerDescriptor_34eMvh4Service'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\CompleteOrder' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.eUZtbq4'] ?? $container->load('get_Messenger_HandlerDescriptor_EUZtbq4Service'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\ShipShipment' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.er8RVdg'] ?? $container->load('get_Messenger_HandlerDescriptor_Er8RVdgService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\ChangePaymentMethod' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.gaPatef'] ?? $container->load('get_Messenger_HandlerDescriptor_GaPatefService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Cart\\ChangeItemQuantityInCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.N3P_9Tt'] ?? $container->load('get_Messenger_HandlerDescriptor_N3P9TtService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Catalog\\AddProductReview' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.bqlGDDc'] ?? $container->load('get_Messenger_HandlerDescriptor_BqlGDDcService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Cart\\BlameCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.YvW1OVE'] ?? $container->load('get_Messenger_HandlerDescriptor_YvW1OVEService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\ChangeShopUserPassword' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.7WZl3GS'] ?? $container->load('get_Messenger_HandlerDescriptor_7WZl3GSService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\RequestResetPasswordToken' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.IkfUGOT'] ?? $container->load('get_Messenger_HandlerDescriptor_IkfUGOTService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\ResendVerificationEmail' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.LQK.Tco'] ?? $container->load('get_Messenger_HandlerDescriptor_LQK_TcoService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\ResetPassword' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.CrE6KL0'] ?? $container->load('get_Messenger_HandlerDescriptor_CrE6KL0Service'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\SendAccountRegistrationEmail' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.UEUxOU_'] ?? $container->load('get_Messenger_HandlerDescriptor_UEUxOUService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\SendAccountVerificationEmail' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.vW0gUG9'] ?? $container->load('get_Messenger_HandlerDescriptor_VW0gUG9Service'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\SendOrderConfirmation' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.Ft4SkrV'] ?? $container->load('get_Messenger_HandlerDescriptor_Ft4SkrVService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\SendResetPasswordEmail' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.KelKxCJ'] ?? $container->load('get_Messenger_HandlerDescriptor_KelKxCJService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\SendShipmentConfirmationEmail' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.IHXeXVj'] ?? $container->load('get_Messenger_HandlerDescriptor_IHXeXVjService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\VerifyCustomerAccount' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.1nnBOav'] ?? $container->load('get_Messenger_HandlerDescriptor_1nnBOavService'));
        }, 1)]));

        $instance->setLogger(($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

        return $instance;
    }
}
