<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_ChannelPricingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.channel_pricing' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Form\Type\Product\ChannelPricingType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Form/Type/Product/ChannelPricingType.php';

        return $container->services['sylius.form.type.channel_pricing'] = new \Sylius\Bundle\CoreBundle\Form\Type\Product\ChannelPricingType('Sylius\\Component\\Core\\Model\\ChannelPricing', $container->parameters['sylius.form.type.channel_pricing.validation_groups'], ($container->services['sylius.repository.channel_pricing'] ?? $container->load('getSylius_Repository_ChannelPricingService')));
    }
}
