<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_CatalogPromotion_Criteria_EnabledService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.catalog_promotion.criteria.enabled' shared service.
     *
     * @return \Sylius\Bundle\PromotionBundle\Criteria\Enabled
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PromotionBundle/Criteria/CriteriaInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PromotionBundle/Criteria/Enabled.php';

        return $container->services['sylius.catalog_promotion.criteria.enabled'] = new \Sylius\Bundle\PromotionBundle\Criteria\Enabled();
    }
}
