<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_AvailableProductOptionValuesResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.available_product_option_values_resolver' shared service.
     *
     * @return \Sylius\Component\Product\Resolver\AvailableProductOptionValuesResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Resolver/AvailableProductOptionValuesResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Resolver/AvailableProductOptionValuesResolver.php';

        return $container->services['sylius.available_product_option_values_resolver'] = new \Sylius\Component\Product\Resolver\AvailableProductOptionValuesResolver();
    }
}
