<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_ProductGenerateVariantsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.product_generate_variants' shared service.
     *
     * @return \Sylius\Bundle\ProductBundle\Form\Type\ProductGenerateVariantsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Form/Type/ProductGenerateVariantsType.php';

        return $container->services['sylius.form.type.product_generate_variants'] = new \Sylius\Bundle\ProductBundle\Form\Type\ProductGenerateVariantsType('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\Product', $container->parameters['sylius.form.type.product_generate_variants.validation_groups'], ($container->services['sylius.form.event_subscriber.product_variant_generator'] ?? $container->load('getSylius_Form_EventSubscriber_ProductVariantGeneratorService')));
    }
}
