<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Grid_FiltersCriteriaResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.grid.filters_criteria_resolver' shared service.
     *
     * @return \Sylius\Component\Grid\Filtering\FiltersCriteriaResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Component/Filtering/FiltersCriteriaResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Component/Filtering/FiltersCriteriaResolver.php';

        return $container->services['sylius.grid.filters_criteria_resolver'] = new \Sylius\Component\Grid\Filtering\FiltersCriteriaResolver();
    }
}
