<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusFixtures_Logger_Formatter_ConsoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_fixtures.logger.formatter.console' shared service.
     *
     * @return \Symfony\Bridge\Monolog\Formatter\ConsoleFormatter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/monolog/monolog/src/Monolog/Formatter/FormatterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/monolog-bridge/Formatter/ConsoleFormatter.php';

        return $container->services['sylius_fixtures.logger.formatter.console'] = new \Symfony\Bridge\Monolog\Formatter\ConsoleFormatter(['format' => '%message% %context% %extra%'."\n".'']);
    }
}
