<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_ZoneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.zone' shared service.
     *
     * @return \Sylius\Bundle\AddressingBundle\Form\Type\ZoneType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AddressingBundle/Form/Type/ZoneType.php';

        return $container->services['sylius.form.type.zone'] = new \Sylius\Bundle\AddressingBundle\Form\Type\ZoneType('Sylius\\Component\\Addressing\\Model\\Zone', $container->parameters['sylius.form.type.zone.validation_groups'], $container->parameters['sylius.scope.zone']);
    }
}
