<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_UniqueIdBasedOrderTokenAssignerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.unique_id_based_order_token_assigner' shared service.
     *
     * @return \Sylius\Component\Core\TokenAssigner\UniqueIdBasedOrderTokenAssigner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/TokenAssigner/OrderTokenAssignerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/TokenAssigner/UniqueIdBasedOrderTokenAssigner.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/Generator/RandomnessGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/Generator/RandomnessGenerator.php';

        return $container->services['sylius.unique_id_based_order_token_assigner'] = new \Sylius\Component\Core\TokenAssigner\UniqueIdBasedOrderTokenAssigner(($container->services['sylius.random_generator'] ?? ($container->services['sylius.random_generator'] = new \Sylius\Component\Resource\Generator\RandomnessGenerator())));
    }
}
