<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Fixture_SimilarProductAssociationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.fixture.similar_product_association' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Fixture\SimilarProductAssociationFixture
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Definition/ConfigurationInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/SimilarProductAssociationFixture.php';

        return $container->services['sylius.fixture.similar_product_association'] = new \Sylius\Bundle\CoreBundle\Fixture\SimilarProductAssociationFixture(($container->services['sylius.fixture.product_association_type'] ?? $container->load('getSylius_Fixture_ProductAssociationTypeService')), ($container->services['sylius.fixture.product_association'] ?? $container->load('getSylius_Fixture_ProductAssociationService')), ($container->services['sylius.repository.product'] ?? $container->load('getSylius_Repository_ProductService')));
    }
}
