<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_ImagesRemoveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.images_remove' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\ImagesRemoveListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/ImagesRemoveListener.php';

        return $container->services['sylius.listener.images_remove'] = new \Sylius\Bundle\CoreBundle\EventListener\ImagesRemoveListener(($container->services['sylius.image_uploader'] ?? $container->load('getSylius_ImageUploaderService')), ($container->services['liip_imagine.cache.manager'] ?? $container->getLiipImagine_Cache_ManagerService()), ($container->services['liip_imagine.filter.manager'] ?? $container->load('getLiipImagine_Filter_ManagerService')));
    }
}
