<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_ApiAuthenticationSuccessListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.listener.api_authentication_success_listener' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\EventListener\AuthenticationSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/EventListener/AuthenticationSuccessListener.php';

        return $container->privates['sylius.listener.api_authentication_success_listener'] = new \Sylius\Bundle\ApiBundle\EventListener\AuthenticationSuccessListener(($container->privates['api_platform.iri_converter'] ?? $container->getApiPlatform_IriConverterService()));
    }
}
