<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_PaymentDescriptionProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.payment_description_provider' shared service.
     *
     * @return \Sylius\Bundle\PayumBundle\Provider\PaymentDescriptionProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Provider/PaymentDescriptionProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Provider/PaymentDescriptionProvider.php';

        return $container->services['sylius.payment_description_provider'] = new \Sylius\Bundle\PayumBundle\Provider\PaymentDescriptionProvider(($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
