<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Registry_TaxCalculationStrategyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.registry.tax_calculation_strategy' shared service.
     *
     * @return \Sylius\Component\Registry\PrioritizedServiceRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['sylius.registry.tax_calculation_strategy'] = $instance = new \Sylius\Component\Registry\PrioritizedServiceRegistry('Sylius\\Component\\Core\\Taxation\\Strategy\\TaxCalculationStrategyInterface', 'Tax calculation strategy');

        $instance->register(($container->services['sylius.taxation.order_items_based_strategy'] ?? $container->load('getSylius_Taxation_OrderItemsBasedStrategyService')), 0);
        $instance->register(($container->services['sylius.taxation.order_item_units_based_strategy'] ?? $container->load('getSylius_Taxation_OrderItemUnitsBasedStrategyService')), 0);

        return $instance;
    }
}
