<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_PromotionCouponGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.promotion_coupon_generator' shared service.
     *
     * @return \Sylius\Component\Promotion\Generator\PromotionCouponGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Promotion/Generator/PromotionCouponGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Promotion/Generator/PromotionCouponGenerator.php';

        return $container->services['sylius.promotion_coupon_generator'] = new \Sylius\Component\Promotion\Generator\PromotionCouponGenerator(($container->services['Sylius\\Component\\Promotion\\Factory\\PromotionCouponFactoryInterface'] ?? $container->load('getPromotionCouponFactoryInterfaceService')), ($container->services['sylius.repository.promotion_coupon'] ?? $container->load('getSylius_Repository_PromotionCouponService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['sylius.promotion_coupon_generator.percentage_policy'] ?? $container->load('getSylius_PromotionCouponGenerator_PercentagePolicyService')));
    }
}
