<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Repository_ProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.repository.product' shared service.
     *
     * @return \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\ProductRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Repository/ProductRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Repository/ProductRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/ProductRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/ProductRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        return $container->services['sylius.repository.product'] = new \BitBag\SyliusMultiVendorMarketplacePlugin\Repository\ProductRepository($a, $a->getClassMetadata('BitBag\\SyliusMultiVendorMarketplacePlugin\\Entity\\Product'), ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
