<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_OrderRecalculationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.order_recalculation' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\OrderRecalculationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/OrderRecalculationListener.php';

        return $container->services['sylius.listener.order_recalculation'] = new \Sylius\Bundle\CoreBundle\EventListener\OrderRecalculationListener(($container->services['sylius.order_processing.order_processor'] ?? $container->load('getSylius_OrderProcessing_OrderProcessorService')));
    }
}
