<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_FormRegistry_PromotionRuleCheckerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form_registry.promotion_rule_checker' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Registry/FormTypeRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Registry/FormTypeRegistry.php';

        $container->services['sylius.form_registry.promotion_rule_checker'] = $instance = new \Sylius\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry();

        $instance->add('cart_quantity', 'default', 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\Rule\\CartQuantityConfigurationType');
        $instance->add('customer_group', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\CustomerGroupConfigurationType');
        $instance->add('nth_order', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\NthOrderConfigurationType');
        $instance->add('shipping_country', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\ShippingCountryConfigurationType');
        $instance->add('has_taxon', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\HasTaxonConfigurationType');
        $instance->add('total_of_items_from_taxon', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\ChannelBasedTotalOfItemsFromTaxonConfigurationType');
        $instance->add('contains_product', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\ContainsProductConfigurationType');
        $instance->add('item_total', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\ChannelBasedItemTotalConfigurationType');

        return $instance;
    }
}
