<?php

namespace ContainerMbsOYIQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Repository_AddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.repository.address' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Doctrine\ORM\AddressRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Repository/AddressRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/AddressRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        return $container->services['sylius.repository.address'] = new \Sylius\Bundle\CoreBundle\Doctrine\ORM\AddressRepository($a, $a->getClassMetadata('Sylius\\Component\\Core\\Model\\Address'));
    }
}
